services:
  backend:
    build:
      context: ./Backend/
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: --bind_ip_all

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database  
      ME_CONFIG_BASICAUTH_USERNAME: admin  
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - database
  

